image:
    file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
# ports:
# - port: 44547
#   onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
    - before: |
          curl -sSfL -o "$HOME/.ssh/github.gpg" https://github.com/nju33/.gitpod/raw/main/.ssh/github.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="$SSH_GITHUB_PASSPHRASE" --output "$HOME/.ssh/github" "$HOME/.ssh/github.gpg"
          chmod 400 "$HOME/.ssh/github"
          git submodule update --init

          .gitpod/before.sh
      init: |
          .gitpod/init.sh

          npm install --location=global firebase-tools
          yarn
      command: |
          .gitpod/command.sh

          rclone mount --allow-non-empty drive:/workspace/gitpod/tirashi-observer-bot "${GITPOD_REPO_ROOT}/projects/$(basename "$GITPOD_REPO_ROOT")" --daemon

vscode:
    extensions:
        - gamunu.vscode-yarn
        - eg2.vscode-npm-script
        - dbaeumer.vscode-eslint
        - esbenp.prettier-vscode
        - TabNine.tabnine-vscode
        - ExodiusStudios.comment-anchors
        - mikestead.dotenv
        - github.vscode-pull-request-github
        - formulahendry.code-runner
        - bierner.markdown-preview-github-styles
        - bierner.markdown-mermaid
        - humao.rest-client
        - foxundermoon.shell-format
        - Orta.vscode-jest
        - christian-kohler.path-intellisense
