// Success message
// https://cloud.nju33.com/UUrcxqQXXunzF0rHilqY

@token = {{$dotenv %LINE_TOKEN}}
@endpoint = https://api.line.me/v2/bot/message/broadcast

###

POST {{endpoint}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

< ./json/chat.json