// https://cloud.nju33.com/nTBRRdqcYwY7yiIYaYlP

@token = {{$dotenv %LINE_TOKEN}}
@endpoint = https://api.line.me/v2/bot/message/broadcast
# @endpoint = https://api.line.me/v2/bot/message/push

###

POST {{endpoint}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

< ./json/image-message.json