// Success message
// https://cloud.nju33.com/FZThJg1BC9gSs648zx7e

@token = {{$dotenv %LINE_TOKEN}}
@endpoint = https://api.line.me/v2/bot/message/broadcast

###

POST {{endpoint}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

< ./json/success.json

###
// Warning message
//

POST {{endpoint}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

< ./json/warning.json

###
// Error message
//

POST {{endpoint}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

< ./json/error.json